services:
  register:
    build:
      context: ..
      dockerfile: backend/register/Dockerfile
    ports:
      - "5004:5000"
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started
      etcd-init:
        condition: service_completed_successfully
    environment:
      - ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
    networks:
      - etcd-net
   
  groups:
    build:
      context: ..
      dockerfile: backend/groups/Dockerfile
    ports:
      - "5005:5000"
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started
      etcd-init:
        condition: service_completed_successfully
    environment:
      - ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
    networks:
      - etcd-net
  
  login:
    build:
      context: ..
      dockerfile: backend/login/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ../.env               # 仍保留共用設定
    environment:
      - SERVICE_NAME=login-service
      - PORT=5001
      - DATABASE_URL=postgresql://user:password@db:5432/tasklistdb  # <── 安全墊
      - ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
    depends_on:
      db:
        condition: service_healthy
      etcd-init:                # <── 確保 etcd key 都寫完
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - etcd-net

  task_list:
    build:
      context: ..
      dockerfile: backend/task_list/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - SERVICE_NAME=task_list
      - PORT=5003
      - DATABASE_URL=postgresql://user:password@db:5432/tasklistdb
      - ETCD_HOST=etcd1
      - ETCD_PORT=2379
    depends_on:
      db:
        condition: service_healthy
    networks:
      - etcd-net

  test:
    build:
      context: ..
      dockerfile: backend/test/Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ../.env
    environment:
      - SERVICE_NAME=test
      - PORT=5002
      - DATABASE_URL=postgresql://user:password@db:5432/tasklistdb
      - ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
    depends_on:
      db:
        condition: service_healthy
      etcd-init:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - etcd-net

  etcd-init:
    build:
      context: ..
      dockerfile: backend/etcd/Dockerfile
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      - ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
    networks:
      - etcd-net

  etcd-watch:
    build:
      context: ..
      dockerfile: backend/etcd/Dockerfile
    command: ["python", "-m", "etcd.watch_database_url"]
    environment:
      - ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    networks:
      - etcd-net

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasklistdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "tasklistdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - etcd-net

  etcd1:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd1
    environment:
      - ETCD_NAME=etcd1
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd1-data:/etcd-data
    networks:
      - etcd-net

  etcd2:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd2
    environment:
      - ETCD_NAME=etcd2
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    ports:
      - "22379:2379"
      - "22380:2380"
    volumes:
      - etcd2-data:/etcd-data
    networks:
      - etcd-net

  etcd3:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd3
    environment:
      - ETCD_NAME=etcd3
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    ports:
      - "32379:2379"
      - "32380:2380"
    volumes:
      - etcd3-data:/etcd-data
    networks:
      - etcd-net

  task_assignment:
    build:
      context: ..
      dockerfile: backend/task_assignment/Dockerfile
    ports:
      - "5007:5000"                # expose 5000 → host 5005
    depends_on:
      db:
        condition: service_healthy
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started
    environment:
      - SERVICE_NAME=task_assignment
      - PORT=5000
      - ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
      - DATABASE_URI=postgresql://user:password@db:5432/tasklistdb
      - TASKLIST_URL=http://tasklist:5002   # 其他服務在同一 network
      - NOTIF_URL=http://notification:5003
    networks:
      - etcd-net

volumes:
  pgdata:
  etcd1-data:
  etcd2-data:
  etcd3-data:

networks:
  etcd-net:

